name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download Go modules
      run: go mod tidy

    - name: Vet Go code
      run: go vet ./...

    - name: Build Go app
      run: go build -v .

    - name: Run tests
      run: |
        if ls *_test.go 1> /dev/null 2>&1; then
          go test -v ./...
        else
          echo "No tests found, skipping..."
        fi